## 271
"""
create class 'Account'

variable : bank_name, user_name, account_num, money

constructor only receive user_name, money
bank_name : 'SC'
account_num : randomly generated by 3-2-6 format
"""
import random


class Account:

  def __init__(self, user_name, money):
    self.bank_name = 'SC'
    self.user_name = user_name

    num1 = random.randint(0, 999)
    num2 = random.randint(0, 99)
    num3 = random.randint(0, 999999)

    num1 = str(num1).zfill(3)
    num2 = str(num2).zfill(2)
    num3 = str(num3).zfill(6)

    self.account_num = f"{num1}-{num2}-{num3}"

    self.money = money


a = Account('a', 1000)
b = Account('b', 2000)
print(a.account_num)
print(b.account_num)

## 272
"""
add class variable 'account_cnt' which counts # of account
"""


class Account:
  account_cnt = 0

  def __init__(self, user_name, money):
    self.bank_name = 'SC'
    self.user_name = user_name

    num1 = random.randint(0, 999)
    num2 = random.randint(0, 99)
    num3 = random.randint(0, 999999)

    num1 = str(num1).zfill(3)
    num2 = str(num2).zfill(2)
    num3 = str(num3).zfill(6)

    self.account_num = f"{num1}-{num2}-{num3}"

    self.money = money
    Account.account_cnt += 1


a = Account('a', 1000)
b = Account('b', 2000)
print(Account.account_cnt)

## 273
"""
create 'class method' get_account_num() which prints account_cnt
"""


class Account:
  account_cnt = 0

  def __init__(self, user_name, money):
    self.bank_name = 'SC'
    self.user_name = user_name

    num1 = random.randint(0, 999)
    num2 = random.randint(0, 99)
    num3 = random.randint(0, 999999)

    num1 = str(num1).zfill(3)
    num2 = str(num2).zfill(2)
    num3 = str(num3).zfill(6)

    self.account_num = f"{num1}-{num2}-{num3}"

    self.money = money
    Account.account_cnt += 1

  @classmethod
  def get_account_num(cls):
    print(cls.account_cnt)


a = Account('a', 1000)
b = Account('b', 2000)
a.get_account_num()
b.get_account_num()

## 274
"""
create method deposit() for putting money
you can only deposit positive value
"""
class Account:
  account_cnt = 0

  def __init__(self, user_name, money):
    self.bank_name = 'SC'
    self.user_name = user_name

    num1 = random.randint(0, 999)
    num2 = random.randint(0, 99)
    num3 = random.randint(0, 999999)

    num1 = str(num1).zfill(3)
    num2 = str(num2).zfill(2)
    num3 = str(num3).zfill(6)

    self.account_num = f"{num1}-{num2}-{num3}"

    self.money = money
    Account.account_cnt += 1

  @classmethod
  def get_account_num(cls):
    print(cls.account_cnt)

  def deposit(self, money):
    if money > 0:
      self.money += money

a = Account('a', 1000)
a.deposit(500)
print(a.money)

## 275
"""
create method withdraw() for taking money
you cannot take more than you have.
"""
class Account:
  account_cnt = 0

  def __init__(self, user_name, money):
    self.bank_name = 'SC'
    self.user_name = user_name

    num1 = random.randint(0, 999)
    num2 = random.randint(0, 99)
    num3 = random.randint(0, 999999)

    num1 = str(num1).zfill(3)
    num2 = str(num2).zfill(2)
    num3 = str(num3).zfill(6)

    self.account_num = f"{num1}-{num2}-{num3}"

    self.money = money
    Account.account_cnt += 1

  @classmethod
  def get_account_num(cls):
    print(cls.account_cnt)

  def deposit(self, money):
    if money > 0:
      self.money += money

  def withdraw(self, money):
    if money <= self.money:
      self.money -= money

a = Account('a', 1000)
a.deposit(500)
print(a.money)
a.withdraw(700)
print(a.money)
a.withdraw(900)
print(a.money)
